### ISSUE TITLE
[Feature Request] Mobile App

### ISSUE THREAD

**Issue by meichthys** [Bible-Projects/believers-sword-next#13]
This may be out of the scope of this project, but it would be really nice to have a mobile version. As this project grows, perhaps this would become feasible.

**Comment by BroJenuel** [comment]
thanks for suggesting, currently working on desktop only but were going to keep this suggestion, and work on it in the future projects. :)

**Comment by passionate2023** [comment]
Looking for a web-version to host it...Meanwhile go through this web-site which beautifully displays the search results and accessibility is awesome...Please think of navigation and search results as much as easy as below...Give a search and explore for few mins

https://english-bible.el-elupath-elu.in/

**Comment by BroJenuel** [comment]
@passionate2023 thanks for the suggestion I will write it in my other todo list and add it if possible :)

**Comment by BroJenuel** [comment]
Going to close this since I am not focused on building as a mobile app..
