### ISSUE TITLE
MacOS/Linux Release

### ISSUE THREAD

**Issue by meichthys** [Bible-Projects/believers-sword-next#28]
Great work, keep it up! It's nice to see all the progress recently.

Are there any plans to have a MacOS or Linux release?

**Comment by BroJenuel** [comment]
Going to add this in my TODo List,,,

currently I am using windows device to build that is why it only builds to windows, hoping I will get a mac laptop or linux  OS so that I can build it to multiple platform.. but for now I will stick to windows OS

**Comment by JenuelDev** [comment]
closing this moved it to a separate task
- https://github.com/Bible-Projects/believers-sword-next/issues/98
- https://github.com/Bible-Projects/believers-sword-next/issues/99
