### ISSUE TITLE
Import Options to import additional Books/Sermons/Dictionaries

### ISSUE THREAD

**Issue by passionate2023** [Bible-Projects/believers-sword-next#37]
Can you please provide import options to import for books/sermons/dictionaries?

a. text file format and sample text file
b. docx file format and sample docx file format
c. import file option to import

**Comment by BroJenuel** [comment]
Thanks for this, I'm going to add this to my to-do list. :) Currently, busy with a lot of stuff but I will definitely be going to add this one. :). If you're creating sermons, I advise you to save them in cloud storage to be backed up. I'll try my best to add functionalities to share your sermons in the application.

**Comment by passionate2023** [comment]
There are many sermons from different preachers i have already have them in text format. Also language dictionaries and books in text format. It would be great if you could do that earlier as i will forward this app to many to use it....

**Comment by passionate2023** [comment]
Please kindly upload some screenshots and steps to import sermons in the main page and in help and here

**Comment by BroJenuel** [comment]
currently not still done with the import but I added a submit sermon button on the sermons page 
![image](https://user-images.githubusercontent.com/31676163/235347836-f06a29bb-ea53-42eb-8316-9ea7559d690b.png)

**Comment by johnmartin2024** [comment]
I also need this of import sermons and do a search. When this will get released?

ex:
martin luther sermons
charles finny sermons
john bunyan sermons
other preacher's text sermons

**Comment by JenuelDev** [comment]
Hi, currently their is an existing to do list where I am going to revamp the sermons page, going to include the import capability on that task.
