### ISSUE TITLE
Exception On Opening in Windows 10 with the latest version

### ISSUE THREAD

**Issue by passionate2023** [Bible-Projects/believers-sword-next#56]
![image](https://github.com/Bible-Projects/believers-sword-next/assets/117767352/9d634f7f-5b55-4159-beb1-8b69afee93ef)

**Comment by BroJenuel** [comment]
I think this is an issue for transitioning from old version to the new version, for now try to uninstall any old believers sword app and installing new here https://github.com/Bible-Projects/believers-sword-next/releases/tag/v0.4.0
