### ISSUE TITLE
Possibility to add a KJV 1769 with Apocrypha as default

### ISSUE THREAD

**Issue by pepaulo** [Bible-Projects/believers-sword-next#70]
I suggest to add the Bible KJV with Apocrypha as default Bible in the App. Reason: possility tô use the same version in default model or with deuterocanonical active model. The version is in public Domain. This free text of the King James Version of the Holy Bible is brought to you courtesy of the Crosswire Bible Society and eBible.org.

**Comment by BroJenuel** [comment]
Hi! It's actually my first time seeing eBible.org. I am going to check and work it out later after work. I'm currently having a big project at work.
