### ISSUE TITLE
Easy way to add New modules

### ISSUE THREAD

**Issue by pepaulo** [Bible-Projects/believers-sword-next#84]
I think that is necessary simplify the adiction modules's methode in Believers Sword. Actually the MyBible module is in a .ZIP Format. A SQLite3 compressed in ZIP.  The list of modules can be used as in Personal Registry list. The example: https://www.dropbox.com/s/49zxxi6b5r9ugen/PePauloGiovanni.registry.json

**Comment by BroJenuel** [comment]
Hi! thanks for the suggestion. Can you give more information or details about this one? :)
