### ISSUE TITLE
Highlight doesn't happen in the verse inside

### ISSUE THREAD

**Issue by passionate2023** [Bible-Projects/believers-sword-next#86]
![image](https://github.com/Bible-Projects/believers-sword-next/assets/117767352/a8f342ae-e53c-4155-880c-b2dcd9b97360)

The highlight happens only on search but after clicking the search result the highlight goes off...

The highlight should appear for viewing the exact verse with highlighted keyword

Please fix this

**Comment by passionate2023** [comment]
![image](https://github.com/Bible-Projects/believers-sword-next/assets/117767352/ae9d44d1-ea5a-48e2-b1f3-d1f0526bcfd4)

**Comment by BroJenuel** [comment]
Added in version 0.4.8
